export { default as PersonalInfo } from './PersonalInfo';
export { default as Summary } from './Summary';
export { default as Skills } from './Skills';
export { default as WorkExperience } from './WorkExperience';
export { default as Projects } from './Projects';
export { default as Education } from './Education';
export { default as GraduationProject } from './GraduationProject';
export { default as Languages } from './Languages';
export { default as OtherSkills } from './OtherSkills';